providers = ["python"]

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --upgrade pip setuptools wheel",
    "pip install -r requirements.txt",
    "mkdir -p models"
]

[phases.build]
cmds = [
    "chmod +x start.py",
    "echo 'Build completed - using demonstration models for Railway deployment'"
]

[start]
cmd = "python start.py"